##############################################################################
#
#  Makefile for Hydra library libEvtChara.so
#
#  This makefile contains all definitions local to this module. All
#  general definitions are included from makefiles in $(HADDIR).
#
##############################################################################

LIB_NAME := EvtChara

SOURCE_FILES :=	hparticleevtcharaBK.cc	

include $(HADDIR)/hades.def.mk
include $(HADDIR)/hades.module.mk
