//
// Created by mikhail on 2/11/21.
//

#ifndef HTREE_TO_AT_SRC_GEANT_WALL_CONVERTER_HADES_TREE_MANAGER_H_
#define HTREE_TO_AT_SRC_GEANT_WALL_CONVERTER_HADES_TREE_MANAGER_H_

class HadesTreeManager {};

#endif // HTREE_TO_AT_SRC_GEANT_WALL_CONVERTER_HADES_TREE_MANAGER_H_
