//
// Created by mikhail on 2/11/21.
//

#ifndef HTREE_TO_AT_SRC_GEANT_WALL_CONVERTER_WALL_HITS_FILLER_H_
#define HTREE_TO_AT_SRC_GEANT_WALL_CONVERTER_WALL_HITS_FILLER_H_

class WallHitsFiller {};

#endif // HTREE_TO_AT_SRC_GEANT_WALL_CONVERTER_WALL_HITS_FILLER_H_
